// Date: 27/12/2012 01:20:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.client.models.trainers;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOrnithologist extends ModelBase
{
  //fields
    ModelRenderer sleepbag;
    ModelRenderer arm_R;
    ModelRenderer arm_L;
    ModelRenderer Leg_L;
    ModelRenderer leg_R;
    ModelRenderer sideL;
    ModelRenderer SideR;
    ModelRenderer belt_L;
    ModelRenderer belt_R;
    ModelRenderer look_L;
    ModelRenderer spy_L;
    ModelRenderer look_R;
    ModelRenderer spy_R;
    ModelRenderer HEADPIECE;
    ModelRenderer BODYPIECE;
    ModelRenderer LEFTLEGPIECE;
    ModelRenderer RIGHTLEGPIECE;
    ModelRenderer main1;
    ModelRenderer main2;
    ModelRenderer head;
    ModelRenderer backpack;
    ModelRenderer adjustor;
    ModelRenderer holder;
    ModelRenderer neck;
    ModelRenderer body;
    ModelRenderer feet_L;
    ModelRenderer feet_R;
  
  public ModelOrnithologist()
  {
    textureWidth = 64;
    textureHeight = 64;
    setTextureOffset("HEADPIECE.Folder1", 0, 0);
    setTextureOffset("BODYPIECE.Folder1", 0, 0);
    setTextureOffset("LEFTLEGPIECE.Folder1", 0, 0);
    setTextureOffset("RIGHTLEGPIECE.Folder1", 0, 0);
    
      sleepbag = new ModelRenderer(this, 0, 45);
      sleepbag.addBox(-4.5F, -1.5F, -1.5F, 9, 3, 3);
      sleepbag.setRotationPoint(0F, -0.5F, 4.5F);
      sleepbag.setTextureSize(64, 64);
      sleepbag.mirror = true;
      setRotation(sleepbag, 0.7853982F, 0F, 0F);
      arm_R.mirror = true;
      arm_R = new ModelRenderer(this, 44, 15);
      arm_R.addBox(-3F, -1F, -2F, 3, 13, 4);
      arm_R.setRotationPoint(-4F, 0F, 0F);
      arm_R.setTextureSize(64, 64);
      arm_R.mirror = true;
      setRotation(arm_R, 0F, 0F, 0.074351F);
      arm_R.mirror = false;
      arm_L = new ModelRenderer(this, 44, 15);
      arm_L.addBox(0F, -1F, -2F, 3, 13, 4);
      arm_L.setRotationPoint(4F, 0F, 0F);
      arm_L.setTextureSize(64, 64);
      arm_L.mirror = true;
      setRotation(arm_L, 0F, 0F, -0.074351F);
      Leg_L.mirror = true;
      Leg_L = new ModelRenderer(this, 0, 15);
      Leg_L.addBox(-2F, 0F, -2.5F, 4, 12, 5);
      Leg_L.setRotationPoint(2F, 10F, 0F);
      Leg_L.setTextureSize(64, 64);
      Leg_L.mirror = true;
      setRotation(Leg_L, 0F, 0F, -0.0174533F);
      Leg_L.mirror = false;
      leg_R = new ModelRenderer(this, 0, 15);
      leg_R.addBox(-2F, 0F, -2.5F, 4, 12, 5);
      leg_R.setRotationPoint(-2F, 10F, 0F);
      leg_R.setTextureSize(64, 64);
      leg_R.mirror = true;
      setRotation(leg_R, 0F, 0F, 0.0174533F);
      sideL = new ModelRenderer(this, 0, 55);
      sideL.addBox(7F, -1.7F, -4F, 2, 1, 8);
      sideL.setRotationPoint(0F, -1.5F, 0F);
      sideL.setTextureSize(64, 64);
      sideL.mirror = true;
      setRotation(sideL, 0F, 0F, -0.6981317F);
      SideR = new ModelRenderer(this, 0, 55);
      SideR.addBox(-9F, -1.7F, -4F, 2, 1, 8);
      SideR.setRotationPoint(0F, -1.5F, 0F);
      SideR.setTextureSize(64, 64);
      SideR.mirror = true;
      setRotation(SideR, 0F, 0F, 0.6981317F);
      belt_L = new ModelRenderer(this, 24, 47);
      belt_L.addBox(0F, -4F, 0F, 1, 4, 0);
      belt_L.setRotationPoint(1F, 2.55F, -3F);
      belt_L.setTextureSize(64, 64);
      belt_L.mirror = true;
      setRotation(belt_L, -0.1396263F, 0F, 0.418879F);
      belt_R = new ModelRenderer(this, 24, 47);
      belt_R.addBox(-1F, -4F, 0F, 1, 4, 0);
      belt_R.setRotationPoint(-1F, 2.55F, -3F);
      belt_R.setTextureSize(64, 64);
      belt_R.mirror = true;
      setRotation(belt_R, -0.1396263F, 0F, -0.418879F);
      look_L = new ModelRenderer(this, 44, 51);
      look_L.addBox(0F, -1.5F, -0.5F, 1, 2, 1);
      look_L.setRotationPoint(0.9F, 2.5F, -4F);
      look_L.setTextureSize(64, 64);
      look_L.mirror = true;
      setRotation(look_L, 0F, -0.2094395F, 0F);
      spy_L = new ModelRenderer(this, 40, 58);
      spy_L.addBox(-0.2F, 0F, -1F, 2, 4, 2);
      spy_L.setRotationPoint(0.9F, 2.5F, -4F);
      spy_L.setTextureSize(64, 64);
      spy_L.mirror = true;
      setRotation(spy_L, 0F, -0.2094395F, 0F);
      look_R = new ModelRenderer(this, 44, 51);
      look_R.addBox(-1F, -1.5F, -0.5F, 1, 2, 1);
      look_R.setRotationPoint(-0.9F, 2.5F, -4F);
      look_R.setTextureSize(64, 64);
      look_R.mirror = true;
      setRotation(look_R, 0F, 0.2094395F, 0F);
      spy_R = new ModelRenderer(this, 40, 58);
      spy_R.addBox(-1.8F, 0F, -1F, 2, 4, 2);
      spy_R.setRotationPoint(-0.9F, 2.5F, -4F);
      spy_R.setTextureSize(64, 64);
      spy_R.mirror = true;
      setRotation(spy_R, 0F, 0.2094395F, 0F);
    HEADPIECE = new ModelRenderer(this, "HEADPIECE");
    HEADPIECE.setRotationPoint(0F, -1.5F, 0F);
    setRotation(HEADPIECE, 0F, 0F, 0F);
    HEADPIECE.mirror = true;
      main2 = new ModelRenderer(this, 0, 53);
      main2.addBox(-5F, -1F, -5F, 10, 1, 10);
      main2.setRotationPoint(0F, -5F, 0F);
      main2.setTextureSize(64, 64);
      main2.mirror = true;
      setRotation(main2, 0F, 0F, 0F);
      main1 = new ModelRenderer(this, 0, 51);
      main1.addBox(-4F, -1F, -6F, 8, 1, 12);
      main1.setRotationPoint(0F, -5F, 0F);
      main1.setTextureSize(64, 64);
      main1.mirror = true;
      setRotation(main1, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3.5F, -8F, -3.5F, 7, 8, 7);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
    BODYPIECE = new ModelRenderer(this, "BODYPIECE");
    BODYPIECE.setRotationPoint(0F, -1F, 0F);
    setRotation(BODYPIECE, 0F, 0F, 0F);
    BODYPIECE.mirror = true;
      adjustor = new ModelRenderer(this, 40, 50);
      adjustor.addBox(-0.5F, -0.5F, -1F, 1, 3, 1);
      adjustor.setRotationPoint(0F, 4F, -3.5F);
      adjustor.setTextureSize(64, 64);
      adjustor.mirror = true;
      setRotation(adjustor, 0F, 0F, 0F);
      holder = new ModelRenderer(this, 40, 54);
      holder.addBox(-1F, 0F, -1.5F, 2, 2, 2);
      holder.setRotationPoint(0F, 4F, -3.5F);
      holder.setTextureSize(64, 64);
      holder.mirror = true;
      setRotation(holder, 0F, 0F, 0F);
      backpack = new ModelRenderer(this, 0, 34);
      backpack.addBox(-3.5F, 0F, 0F, 7, 8, 3);
      backpack.setRotationPoint(0F, 0F, 2.5F);
      backpack.setTextureSize(64, 64);
      backpack.mirror = true;
      setRotation(backpack, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 28, 0);
      neck.addBox(-2.5F, -8F, -2.5F, 5, 2, 5);
      neck.setRotationPoint(0F, 6.5F, 0F);
      neck.setTextureSize(64, 64);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      body = new ModelRenderer(this, 18, 15);
      body.addBox(-4F, 0F, -2.5F, 8, 11, 5);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
    LEFTLEGPIECE = new ModelRenderer(this, "LEFTLEGPIECE");
    LEFTLEGPIECE.setRotationPoint(2F, 10F, 0F);
    setRotation(LEFTLEGPIECE, 0F, 0F, 0F);
    LEFTLEGPIECE.mirror = true;
      feet_L = new ModelRenderer(this, 20, 32);
      feet_L.addBox(-2.2F, 12F, -4.5F, 4, 3, 7);
      feet_L.setRotationPoint(0F, -1F, 0F);
      feet_L.setTextureSize(64, 64);
      feet_L.mirror = true;
      setRotation(feet_L, 0F, 0F, -0.0174533F);
    RIGHTLEGPIECE = new ModelRenderer(this, "RIGHTLEGPIECE");
    RIGHTLEGPIECE.setRotationPoint(-2F, 10F, 0F);
    setRotation(RIGHTLEGPIECE, 0F, 0F, 0F);
    RIGHTLEGPIECE.mirror = true;
      feet_R = new ModelRenderer(this, 20, 32);
      feet_R.addBox(-5.8F, 12F, -4.5F, 4, 3, 7);
      feet_R.setRotationPoint(4F, -1F, 0F);
      feet_R.setTextureSize(64, 64);
      feet_R.mirror = true;
      setRotation(feet_R, 0F, 0F, 0.0174533F);
      
      HEADPIECE.addChild(head);
      HEADPIECE.addChild(main2);
      HEADPIECE.addChild(main1);
      HEADPIECE.addChild(sideL);
      HEADPIECE.addChild(SideR);
      
      BODYPIECE.addChild(adjustor);
      BODYPIECE.addChild(holder);
      BODYPIECE.addChild(backpack);
      BODYPIECE.addChild(neck);
      BODYPIECE.addChild(body);
      
      LEFTLEGPIECE.addChild(feet_L);
      
      RIGHTLEGPIECE.addChild(feet_R);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    sleepbag.render(f5);
    arm_R.render(f5);
    arm_L.render(f5);
    Leg_L.render(f5);
    leg_R.render(f5);
    sideL.render(f5);
    SideR.render(f5);
    belt_L.render(f5);
    belt_R.render(f5);
    look_L.render(f5);
    spy_L.render(f5);
    look_R.render(f5);
    spy_R.render(f5);
    HEADPIECE.render(f5);
    BODYPIECE.render(f5);
    LEFTLEGPIECE.render(f5);
    RIGHTLEGPIECE.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {

  }

}
